server {
  listen 80;
  listen [::]:80;

  location / {
    root /usr/share/nginx/html;

    rewrite ^/config.json$ /config.json break;
    rewrite ^/manifest.json$ /manifest.json break;

    rewrite ^/sw.js$ /sw.js break;
    rewrite ^/pdf.worker.min.js$ /pdf.worker.min.js break;

    rewrite ^/favicon\.svg$ /favicon.svg break;
    rewrite ^/favicon\.ico$ /favicon.ico break;
    rewrite ^/favicon-192x192\.png$ /favicon-192x192.png break;
    rewrite ^/favicon-512x512\.png$ /favicon-512x512.png break;
    rewrite ^/apple-touch-icon\.png$ /apple-touch-icon.png break;

    rewrite ^/public/(.*)$ /public/$1 break;
    rewrite ^/assets/(.*)$ /assets/$1 break;

    rewrite ^(.+)$ /index.html break;
  }
}
